#!/usr/bin/bash
# install
# install script for wslu
# <https://github.com/wslutilities/wslu>
# Copyright (C) 2019 Patrick Wu
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
BUILD_DIR=`mktemp --tmpdir --directory wslu-install.XXXX`
git clone -b develop https://github.com/wslutilities/wslu $BUILD_DIR
cd $BUILD_DIR
bash configure.sh -i
sudo install -m755 extras/scripts/wslu-uninstall /usr/bin
rm -rf $BUILD_DIR
echo -e "\e[32m## wslu installation complete. To uninstall, run 'wslu-uninstall'\033(B\033[m"
